# coding: utf-8

"""
    Fabric Credential Manager API

    This is Fabric Credential Manager API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kthare10@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fabric_credmgr
from fabric_credmgr.models.refresh_revoke_request import RefreshRevokeRequest  # noqa: E501
from fabric_credmgr.rest import ApiException


class TestRefreshRevokeRequest(unittest.TestCase):
    """RefreshRevokeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefreshRevokeRequest(self):
        """Test RefreshRevokeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fabric_credmgr.models.refresh_revoke_request.RefreshRevokeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
