# coding: utf-8

"""
    Fabric Credential Manager API

    This is Fabric Credential Manager API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kthare10@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fabric_credmgr
from fabric_credmgr.models.cred_mgr_response import CredMgrResponse  # noqa: E501
from fabric_credmgr.rest import ApiException


class TestCredMgrResponse(unittest.TestCase):
    """CredMgrResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredMgrResponse(self):
        """Test CredMgrResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fabric_credmgr.models.cred_mgr_response.CredMgrResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
