# coding: utf-8

"""
    Fabric Credential Manager API

    This is Fabric Credential Manager API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kthare10@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CredMgrResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'message': 'str',
        'value': 'CredMgrResponseValue',
        'version': 'str'
    }

    attribute_map = {
        'status': 'status',
        'message': 'message',
        'value': 'value',
        'version': 'version'
    }

    def __init__(self, status=None, message=None, value=None, version=None):  # noqa: E501
        """CredMgrResponse - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._message = None
        self._value = None
        self._version = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if message is not None:
            self.message = message
        if value is not None:
            self.value = value
        if version is not None:
            self.version = version

    @property
    def status(self):
        """Gets the status of this CredMgrResponse.  # noqa: E501

        status code  # noqa: E501

        :return: The status of this CredMgrResponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CredMgrResponse.

        status code  # noqa: E501

        :param status: The status of this CredMgrResponse.  # noqa: E501
        :type: int
        """
        if status is not None and status < 0:  # noqa: E501
            raise ValueError("Invalid value for `status`, must be a value greater than or equal to `0`")  # noqa: E501

        self._status = status

    @property
    def message(self):
        """Gets the message of this CredMgrResponse.  # noqa: E501

        status message  # noqa: E501

        :return: The message of this CredMgrResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CredMgrResponse.

        status message  # noqa: E501

        :param message: The message of this CredMgrResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def value(self):
        """Gets the value of this CredMgrResponse.  # noqa: E501


        :return: The value of this CredMgrResponse.  # noqa: E501
        :rtype: CredMgrResponseValue
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this CredMgrResponse.


        :param value: The value of this CredMgrResponse.  # noqa: E501
        :type: CredMgrResponseValue
        """

        self._value = value

    @property
    def version(self):
        """Gets the version of this CredMgrResponse.  # noqa: E501

        Actor version  # noqa: E501

        :return: The version of this CredMgrResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this CredMgrResponse.

        Actor version  # noqa: E501

        :param version: The version of this CredMgrResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CredMgrResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CredMgrResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
